name: covid_19_dashboard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.0.0
  line_awesome_icons: ^1.0.4+2
  pie_chart: ^3.1.1
  intl: ^0.16.1
  http: ^0.12.1
  url_launcher: ^5.4.5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
